name: "Build Docker Image"
description: "Re-usable docker image build"
inputs:
  apple:
    description: 'Api base URL'
    required: true

runs:
  using: "composite"
  steps:
    - name: Build docker file
      run: echo ${{ input.apple }}
      shell: sh
