name: Api build

on:
  push:
    branches-ignore: [$default-branch]

env:
  DAY_OF_WEEK: Monday

jobs:
  api_build:
    container: docker/compose:latest
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Print
        run: echo $DAY_OF_WEEK
